### ISSUE TITLE
Losing `event.currentTarget`

### ISSUE THREAD

**Issue by raine** [Frezc/use-lodash-debounce-throttle#1]
I changed a regular callback `onMouseMove` to use this library, and it seems that sometimes, but not always, `event.currentTarget` is `null` in the callback. That does not happen without `useThrottle`.

**Comment by Frezc** [comment]
It's a common issue with debounce/throttle because the Event object will be mutated after listeners called. 

Solution:
Pass currentTarget to throttled function
```javascript
const fn = useThrottle((currentTarget) => {
  console.log(currentTarget);
});

return (
  <div onMouseMove={(e) => fn(e.currentTarget)} />
);
```
